Доработана функциональность по техническому заданию 7 спринта.
kkn365/java-kanban pull request #2
Opened 2024-05-12 15:41 UTC by kkn365

2024-05-13 14:49 UTC, YazykovMikhail commented
Добавь в заадчи поле TaskType taskType
или еще проще сделай метод для каждой задачи 
public TaskType getType() {
		return TaskType.TASK;
	}
который будет возвращать свой тип.

2024-05-13 14:56 UTC, YazykovMikhail commented
Сделай все поля protected в классе InMemoryTaskManager, что бы у наследника был прямой доступ до полей

2024-05-13 15:04 UTC, YazykovMikhail requested changes

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +    static File fileName;
Забыл модификатор доступа
Статичным делать не нужно, у кажого инстаса приложения должен быть свой файл
поле лучше нзвать file, ведь это не просто имя файла
private final File file;

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +        } else if (task instanceof Subtask) {
Использу TaskType, рефлексия - это последние к чему стоит прибегать

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +    String toString(Task task) {
```
	private String toString(Task task) {
		return task.getId() + "," + task.getType() + "," + task.getName() + "," + task.getStatus() + "," + task.getDescription() + "," + (task.getType().equals(TaskType.SUBTASK) ? task.getEpicId() : "");
	}
```
Как можно просто сделать, или доработай свое решение с использование TaskType

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +            case "TASK":
Используй TaskType

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +
Переопределны должны быть все методы которые влияют на состояние, добавление/обновление/удаление, ведь состояние приложения меняетя

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +    private void save(Task task) throws ManagerSaveException {
Метод сохранения должен сохранять полностью все состояние приложения, а не конкретной зазачи.


СПОЙЛЕР:
	```
protected void save() {
		try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
			writer.write(HEADER);
			writer.newLine();

			for (Map.Entry<Integer, Task> entry : tasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Subtask> entry : subtasks.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			for (Map.Entry<Integer, Epic> entry : epics.entrySet()) {
				final Task task = entry.getValue();
				writer.write(CSVTaskFormat.toString(task));
				writer.newLine();
			}

			writer.newLine();
		} catch (IOException e) {
			throw new ManagerSaveException("Can't save to file: " + file.getName(), e);
		}
	}
```

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/exceptions/ManagerSaveException.java
> +public class ManagerSaveException extends Exception {
Стоит наследовать от RuntimeException
что бы не было обязательной обработки, это исключение будет уведомлять об ошибке с которой в рамках приложения нельзя ничего сделать

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +            System.out.println("Произошла ошибка во время чтения файла.");
Стоит выбрасывать исключение, иначе непонятно получилось востановить работу или нет. 
Мы уже не работает в консоли, если нет никакой ошибки значит все хорошо, в консоль будут смотреть только тогда когда будет ошибка, что бы разобраться откуда она взялась
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/exceptions/ManagerSaveException.java
> +public class ManagerSaveException extends Exception {
Базовое обьявление кастомного исключения:
```
public class ManagerSaveException extends RuntimeException {
	public ManagerSaveException() {
	}

	public ManagerSaveException(String message) {
		super(message);
	}

	public ManagerSaveException(String message, Throwable cause) {
		super(message, cause);
	}

	public ManagerSaveException(Throwable cause) {
		super(cause);
	}

}
```

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +
Файл лучше устанавливать во время старта приложения, что бы приложения работало именно с ним
	public FileBackedTaskManager(File file) {
		this.file = file;
	}

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +        fileName = filename;
Файл устанавливается через конструктор

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/util/Managers.java
> +    public static FileBackedTaskManager getDefaultFileManager() {
public static TaskManager getDefault() {
		return new FileBackedTaskManager(new File("resources/task.csv"));
	}

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/util/Managers.java
> +    public static FileBackedTaskManager getDefaultFileManager() {
Обрати внимание в какой папке стоит хранит файл

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +                    taskManager.addNewTask(task);
не стоит использовать методы добавления, ведь там создается новый идентификатор, а нужно восстановить имено те идентификаторы что были, они могли идти не по порядку. Лучше напрямую добавлять задачи в хранилище

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +                Task task = new Task(split[2], split[4]);
сделай конструктор на все поля, что бы созадвать задачу одной строкой и не делать потом set

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +            }
Так же стоит восстанавливать счетчик идентификаторов, что бы приложение продолжило работать дальше.

2024-05-13 15:04 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/FileBackedTaskManager.java
> +    public static FileBackedTaskManager loadFromFile(File filename) {
В связи с комментариями ниже:
СПОЙЛЕР:

```
	public static FileBackedTaskManager loadFromFile(File file) {
		final FileBackedTaskManager taskManager = new FileBackedTaskManager(file);
		try {
			final String csv = Files.readString(file.toPath());
			final String[] lines = csv.split(System.lineSeparator());
			int generatorId = 0;
			for (int i = 1; i < lines.length; i++) {
				String line = lines[i];
				if (line.isEmpty()) {
					break;
				}
				final Task task = taskFromString(line);
				final int id = task.getId();
				if (id > generatorId) {
					generatorId = id;
				}
				taskManager.addAnyTask(task);
			}
			for (Map.Entry<Integer, Subtask> e : taskManager.subtasks.entrySet()) {
				final Subtask subtask = e.getValue();
				final Epic epic = taskManager.epics.get(subtask.getEpicId());
				epic.addSubtaskId(subtask.getId());
			}
			taskManager.generatorId = generatorId;
		} catch (IOException e) {
			throw new ManagerSaveException("Can't read form file: " + file.getName(), e);
		}
		return taskManager;
	}
```

2024-05-14 19:58 UTC, kkn365 commented
Михаил, привет!
Огромное спасибо за комментарии. Без твоей помощи, однозначно не разобрался бы с задачей.

2024-05-15 05:49 UTC, YazykovMikhail approved these changes

2024-05-15 05:49 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/manager/InMemoryTaskManager.java
> +    public void addAnyTask(Task task) {
Этот метод лучше вынести в FileBackedTaskManager  и сделать приватным. 
Ведь он нужен только для восстановления

2024-05-15 05:49 UTC, YazykovMikhail commented on src/ru/yandex/javacource/kvitchenko/schedule/Main.java
А зачем Main удалил?
Точка входа должна быть. Стоит вернуть, если там есть проблемы со стораыми тестами, их можно удалить

2024-06-10 16:07 UTC, merged